const localisation = {
  translation: {
    NAV_MENU_PLAN: "About the event",
    NAV_MENU_REGISTER: "Registration/tickets",
    NAV_MENU_PARTICIPANTS: "Participants",
    NAV_MENU_SPEAKERS: "Speakers",
    NAV_MENU_DISCO: "New Year's disco",
    BANNER_SUBTITLE: "Maximum opportunities - many innovations - dozens of fun",
    REGISTRATION: "Registration",
    BANNER_DATE: "15th of December / Wednesday",
    ABOUT_TITLE: "The largest in Europe, the first international forum of nail industry",
    ABOUT_ITEM1: "Presentation of new collections in 2022 from the world's best manufacturers",
    // ABOUT_ITEM2: "The world's first show Nail Fashion Day",
    ABOUT_ITEM3: "Speeches by top speakers of the beauty industry",
    ABOUT_ITEM4: "The latest trends and technologies from masters of nail aesthetics",
    ABOUT_ITEM5: "New Year's corporate party \" Nail New Year\" accompanied by an incendiary cover band  \" Wunderkind\"",
    ROAD_MAP: "Road map",
    LOCATION: "Shopping center \" Gorodok Gallery\" ",
    STATISTICS_VISITORS: "Visitors associated with the nail industry",
    STATISTICS_NAILBUYERS: "Nail buyers will take part in the event",
    STATISTICS_COMPANY: "Manufacturers will take part in the event",
    STATISTICS_EXPERTS: "World-renowned experts among our speakers",
    PROGRAM_TITLE: 'Event plan',
    PROGRAM_ITEM: 'Registration',
    PROGRAM_ITEM1: 'The DJ works',
    PROGRAM_ITEM2: 'Welcome speech from the organizers',
    PROGRAM_ITEM3: 'Presentations',
    PROGRAM_ITEM4: 'Nail Fashion Day show',
    PROGRAM_ITEM5: 'New Years corporate party',
    PROGRAM_ITEM6: 'Speaker',
    BUTTON_CLICK: 'Collapse',
    BUTTON_ALL: 'All program',
    SAFETY_MEASURES: "Safety measures",
    PROTECTION_MEANS: 'Means of protection',
    PROTECTION_MEANS_SUBTITLE: 'Admission to the conference is only in a mask. Antiseptics around the perimeter.',
    TEMPERATURE_SCREENING: 'Temperature screening on entrance',
    TEMPERATURE_SCREENING_SUBTITLE: 'Measurement of body temperature for each visitor.',
    FOOD_TITLE: 'Safe food',
    FOOD_SUBTITLE: 'During the coffee break, each person is given individual dishes.',
    PASSPORT_TITLE: 'PCR test or a vaccination certificate',
    RESTRICTIONS_TITLE: 'Compliance with requirements of the Ministry of Healthcare of Ukraine',
    RESTRICTIONS_SUBTITLE: 'The number of attendees is restricted in accordance with the rules of holding mass events.',
    DISTANCE_TITLE: 'Social distancing',
    DISTANCE_SUBTITLE: 'The distance between chairs in the conference hall is not less than 1.5 meters.',
    FOOTER_COL_ADVERTISING: 'Website development and creation',
    STILL: 'Still have questions about the event?',
    STILL_WRITE: 'Write to us!',
    BUY_TICKET: 'buy a ticket',
    MASTERS: 'masters',
    MEMBERS: 'members',
    BUYERS: 'buyers',
    LEARN_MORE: 'Do you still have questions? Write to us!',
    LEARN_MORE_WRITE: 'To write',
    LEARN_MORE1: 'Are you a manufacturer? Take part!',
    LEARN_MORE_WRITE1: 'Apply',
    LEARN_MORE_US: 'Ready to write cool about us? Collaborate!',
    LEARN_MORE_WRITE2: 'Cooperate',
    LEARN_MORE_MASTER: 'Experienced master or beginning? Join us!',
    LEARN_MORE_WRITE3: 'Join',
    LEARN_MORE_LOGO: 'Do you want everyone to see your logo? Sponsor!',
    LEARN_MORE_WRITE4: 'To sponsor',
  }
};

export default localisation;