const localisation = {
  translation: {
    NAV_MENU_PLAN: "About the event",
    NAV_MENU_REGISTER: "Tickets",
    NAV_MENU_PARTICIPANTS: "Manufacturer",
    NAV_MENU_SPEAKERS: "Speakers",
    NAV_MENU_DISCO: "New Year's disco",
    BANNER_SUBTITLE: "Maximum opportunities - maximum pleasure!",
    REGISTRATION: "Register now",
    BANNER_DATE: "15th of Dec / Wed",
    ABOUT_TITLE: "The largest international forum of nail aesthetics in Europe",
    ABOUT_ITEM1: "Presentation of new collections in 2022 from the world's best manufacturers",
    ABOUT_ITEM2: "The world's first Fashion Nail Show",
    ABOUT_ITEM3: "Speeches by top speakers of the beauty industry",
    ABOUT_ITEM4: "The latest trends and technologies from masters of nail aesthetics",
    ABOUT_ITEM5: "Party and show program for all forum participants",
    ROAD_MAP: "Road map",
    LOCATION: "Shopping center \" Gorodok Gallery\" 3rd floor",
    LOCATION1: "Stepan Bandera Avenue 23,",
    STATISTICS_VISITORS: "Visitors associated with the nail industry",
    STATISTICS_NAILBUYERS: "Nail buyers will take part in the event",
    STATISTICS_COMPANY: "Leading manufacturers of the nail industry",
    STATISTICS_EXPERTS: "Top practicing speakers",
    SPEAKERS_TITLE: "industry tops",
    SPEAKER1: 'Irina Zaitseva',
    SPEAKER1_DESC: 'Television expert of top TV projects of Ukraine. Founder and organizer of "Mrs. Ukraine", co-organizer and member of the jury of international beauty contests',
    SPEAKER2: 'Maria Plyakhovska',
    SPEAKER2_DESC: 'Professional coach, Isaak Pintosevich System. Public figure, successful businesswoman',
    PROGRAM_TITLE: 'In the forum program:',
    PROGRAM_ITEM: 'Registration',
    PROGRAM_ITEM1: 'The DJ works',
    PROGRAM_ITEM2: 'Welcome speech from the organizers',
    PROGRAM_ITEM3: 'Presentations',
    PROGRAM_ITEM4: 'Nail Fashion Day show',
    PROGRAM_ITEM5: 'New Years corporate party',
    PROGRAM_ITEM6: 'Speaker',
    RETAILERS: 'Information for retailers',
    RETAILERS_TITLE: 'With us you can:',
    RETAILERS_TEXT: 'Get direct communication with potential domestic and foreign users of your products - the forum is planned to be attended by more than 1,500 manicurists, owners of beauty salons, studios and schools',
    RETAILERS_TEXT1: 'The most effective way to present your trading platform exclusively to the target audience - our event brings together the best nail service professionals who will come to see next year\'s trends',
    RETAILERS_TEXT2: 'Realize the most creative fantasies of your team - we present the world\'s first grand "Nail Fashion Show", where your model will be seen all over Ukraine',
    // RETAILERS_TEXT3: 'Announce yourself across the country - Nano Tech Nail plans to cover leading media',
    // RETAILERS_TEXT4: 'Conduct effective negotiations and get profitable contracts during the forum - we gather only the best and only with new ones. You have to see it first! And your customers have to be the first to get it!',
    BUTTON_CLICK: 'Collapse',
    BUTTON_ALL: 'All program',
    SAFETY_MEASURES: "Safety measures",
    PROTECTION_MEANS: 'Means of protection',
    PROTECTION_MEANS_SUBTITLE: 'Admission to the conference is only in a mask. Antiseptics around the perimeter.',
    TEMPERATURE_SCREENING: 'Temperature screening on entrance',
    TEMPERATURE_SCREENING_SUBTITLE: 'Measurement of body temperature for each visitor',
    FOOD_TITLE: 'Safe food',
    FOOD_SUBTITLE: 'During the coffee break, each person is given individual dishes.',
    PASSPORT_TITLE: 'PCR test or a vaccination certificate',
    RESTRICTIONS_TITLE: 'Compliance with requirements of the Ministry of Healthcare of Ukraine',
    RESTRICTIONS_SUBTITLE: 'The number of attendees is restricted in accordance with the rules of holding mass events.',
    DISTANCE_TITLE: 'Social distancing',
    DISTANCE_SUBTITLE: 'The distance between chairs in the conference hall is not less than 1.5 meters.',
    FOOTER_COL_ADVERTISING: 'Website development and creation',
    STILL: 'Still have questions about the event?',
    STILL_WRITE: 'Write to us!',
    BUY_TICKET: 'buy a ticket',
    CALC: 'Detail calculation',
    MASTERS: 'masters',
    FOR_VISITORS: 'Visitors',
    MEMBERS: 'Members',
    BUYERS: 'buyers',
    LEARN_MORE: 'Still have questions? Write / call us! We will answer everything!',
    LEARN_MORE_WRITE: 'To write',
    LEARN_MORE1: 'Are you a manufacturer? Take part!',
    LEARN_MORE_WRITE1: 'Apply',
    LEARN_MORE_US: 'Ready to write cool about us? Collaborate!',
    LEARN_MORE_WRITE2: 'Cooperate',
    LEARN_MORE_MASTER: 'Experienced craftsman or beginner? Join us!',
    LEARN_JOIN: 'Join',
    LEARN_MORE_WRITE3: 'Order feedback',
    LEARN_MORE_LOGO: 'Do you have a point of sale? This is your territory!',
    LEARN_MORE_WRITE4: 'To sponsor',
    YOU_WANT: 'Most modern Fashion Day in beauty industry!',
    YOU_WANT1: 'For you if you want:',
    YOU_WANT2: 'be the first to know about the trends of the season 2022',
    YOU_WANT3: 'test new items of world brands',
    YOU_WANT4: 'hear about the trends of the nail industry of the future',
    YOU_WANT5: 'get inspired by new ideas and find new acquaintances',
    ORGANIZER: 'Organizer:',
    ORGANIZER_DECS: 'A series of forums on the latest technologies and promising developments in the beauty industry.',
    ORGANIZER_DECS1: 'The main trends in the field of nail industry, lash & brow and cosmetology',
    ORGANIZER_AGITATION: 'Anything you need - ',
    ORGANIZER_FOR: 'for craftsmen, schools, studios, salons',
    ORGANIZER_OR: 'or',
    BONUS: 'A nice bonus for guests and participants - New Year\'s corporate party for inflammatory hits from Cover band "WunderkindЫ"\' and DJ Andrew Sosed',
    BONUS_GIFT: 'Gifts from sponsors and partners',
    // BONUS_GIFT1: 'Unlimited space for professional growth and networking!',
    // BONUS_TEXT: 'Light together',
    // BONUS_TEXT1: 'Learning new',
    // BONUS_TEXT2: 'We share the best',
    // BONUS_TEXT3: 'We smile sincerely',
    BONUS_TEXT4: 'Fair of novelties, business contacts, perspective connections and great mood!',
    BONUS_TEXT5: 'December 15, 2021! Kyiv,',
    BONUS_TEXT6: 'Your ticket to the world of Nano Tech Nail is waiting for you HERE:',
    PARTICIPATION_TITLE: 'Participation package for manufacturers',
    PARTICIPATION_ITEM_TITLE1: 'Presentation of the 2022 collections',
    PARTICIPATION_ITEM_TITLE2: 'Participation in Nail Fashion Day',
    PARTICIPATION_ITEM_TITLE3: 'Advertising package',
    PARTICIPATION_ITEM_TITLE4: 'Exhibition area',
    PARTICIPATION_ITEM_TITLE5: 'Business networking',
    PARTICIPATION_ITEM_TITLE6: 'Expansion of markets',
    PARTICIPATION_ITEM_DESCRIPTION1: 'Direct communication with potential domestic and foreign users of your products',
    PARTICIPATION_ITEM_DESCRIPTION2: 'The world\'s first grand "Nail Fashion Show", where the whole of Ukraine will see your model.',
    PARTICIPATION_ITEM_DESCRIPTION3: 'The full range of promotion in the Internet resources of the organizers.',
    PARTICIPATION_ITEM_DESCRIPTION4: 'Personal stand in the exhibition area, among all visitors',
    PARTICIPATION_ITEM_DESCRIPTION5: 'The trade missions of several countries in Europe and Asia take part in Nano Tech Nail',
    PARTICIPATION_ITEM_DESCRIPTION6: 'The forum will be attended by about a hundred buyers and retailers who will see your new products',
  }
};

export default localisation;