const localisation = {
  translation: {
    NAV_MENU_PLAN: "About the event",
    NAV_MENU_REGISTER: "Tickets",
    NAV_MENU_PARTICIPANTS: "Manufacturer",
    NAV_MENU_SPEAKERS: "Speakers",
    NAV_MENU_DISCO: "New Year's disco",
    BANNER_SUBTITLE: "Maximum opportunities - maximum pleasure!",
    // REGISTRATION: "Registration",
    BANNER_DATE: "15th of December / Wednesday",
    ABOUT_TITLE: "For the first time in Europe! The largest international forum of nail aesthetics",
    ABOUT_ITEM1: "Presentation of new collections in 2022 from the world's best manufacturers",
    ABOUT_ITEM2: "The world's first show Nail Fashion Day",
    ABOUT_ITEM3: "Speeches by top speakers of the beauty industry",
    ABOUT_ITEM4: "The latest trends and technologies from masters of nail aesthetics",
    ABOUT_ITEM5: "Party and show program for all forum participants",
    ROAD_MAP: "Road map",
    LOCATION: "Shopping center \" Gorodok Gallery\" ",
    STATISTICS_VISITORS: "Visitors associated with the nail industry",
    STATISTICS_NAILBUYERS: "Nail buyers will take part in the event",
    STATISTICS_COMPANY: "Leading manufacturers of the nail industry",
    STATISTICS_EXPERTS: "Top practicing speakers",
    PROGRAM_TITLE: 'In the forum program:',
    PROGRAM_ITEM: 'Registration',
    PROGRAM_ITEM1: 'The DJ works',
    PROGRAM_ITEM2: 'Welcome speech from the organizers',
    PROGRAM_ITEM3: 'Presentations',
    PROGRAM_ITEM4: 'Nail Fashion Day show',
    PROGRAM_ITEM5: 'New Years corporate party',
    PROGRAM_ITEM6: 'Speaker',
    BUTTON_CLICK: 'Collapse',
    BUTTON_ALL: 'All program',
    SAFETY_MEASURES: "Safety measures",
    PROTECTION_MEANS: 'Means of protection',
    PROTECTION_MEANS_SUBTITLE: 'Admission to the conference is only in a mask. Antiseptics around the perimeter.',
    TEMPERATURE_SCREENING: 'Temperature screening on entrance',
    TEMPERATURE_SCREENING_SUBTITLE: 'Measurement of body temperature for each visitor.',
    FOOD_TITLE: 'Safe food',
    FOOD_SUBTITLE: 'During the coffee break, each person is given individual dishes.',
    PASSPORT_TITLE: 'PCR test or a vaccination certificate',
    RESTRICTIONS_TITLE: 'Compliance with requirements of the Ministry of Healthcare of Ukraine',
    RESTRICTIONS_SUBTITLE: 'The number of attendees is restricted in accordance with the rules of holding mass events.',
    DISTANCE_TITLE: 'Social distancing',
    DISTANCE_SUBTITLE: 'The distance between chairs in the conference hall is not less than 1.5 meters.',
    FOOTER_COL_ADVERTISING: 'Website development and creation',
    STILL: 'Still have questions about the event?',
    STILL_WRITE: 'Write to us!',
    BUY_TICKET: 'buy a ticket',
    MASTERS: 'masters',
    MEMBERS: 'members',
    BUYERS: 'buyers',
    LEARN_MORE: 'Still have questions? Write / call us! We will answer everything!',
    LEARN_MORE_WRITE: 'To write',
    LEARN_MORE1: 'Are you a manufacturer? Take part!',
    LEARN_MORE_WRITE1: 'Apply',
    LEARN_MORE_US: 'Ready to write cool about us? Collaborate!',
    LEARN_MORE_WRITE2: 'Cooperate',
    LEARN_MORE_MASTER: 'Experienced master or beginning? Join us!',
    LEARN_MORE_WRITE3: 'Join',
    LEARN_MORE_LOGO: 'Do you want everyone to see your logo? Sponsor!',
    LEARN_MORE_WRITE4: 'To sponsor',
    YOU_WANT: 'Most modern Fashion Day in beauty industry!',
    YOU_WANT1: 'For you if you want:',
    YOU_WANT2: 'be the first to know about the trends of the season 2022',
    YOU_WANT3: 'test new items of world brands',
    YOU_WANT4: 'hear about the trends of the nail industry of the future',
    YOU_WANT5: 'get inspired by new ideas and find new acquaintances',
    ORGANIZER: 'Organizer:',
    ORGANIZER_DECS: 'A series of forums on the latest technologies and promising developments in the beauty industry',
    ORGANIZER_AGITATION: 'Anything you need - ',
    ORGANIZER_OR: 'or',
    BONUS: 'A nice bonus for guests and participants - New Year\'s corporate party for inflammatory hits from Cover band "Wunderkind"\'',
    BONUS_GIFT: 'Gifts from sponsors and partners',
    BONUS_GIFT1: 'Unlimited space for professional growth and networking!',
    BONUS_TEXT: 'Light together',
    BONUS_TEXT1: 'We are learning something new',
    BONUS_TEXT2: 'We share the best',
    BONUS_TEXT3: 'We smile sincerely',
    BONUS_TEXT4: 'Fair of novelties, business contacts, perspective connections and great mood!',
    BONUS_TEXT5: 'February 15, 2021! Kyiv,',
    BONUS_TEXT6: 'Your ticket to the world of Nano Tech Nail is waiting for you HERE:',
  }
};

export default localisation;