const localisation = {
  translation: {
    NAV_MENU_PLAN: "Пpo захiд",
    NAV_MENU_REGISTER: "Реєстрація/квитки",
    NAV_MENU_PARTICIPANTS: "Учасники",
    NAV_MENU_SPEAKERS: "Спікери",
    NAV_MENU_DISCO: "Новорічна дискотека",
    BANNER_SUBTITLE: "Максимум можливостей - безліч інновацій – море задоволень",
    REGISTRATION: "Реєстрація",
    BANNER_DATE: "15 грудня / середа",
    ABOUT_TITLE: "Найбільший в Європі, Перший міжнародний форум нігтьової індустрії",
    ABOUT_ITEM1: "Презентація нових колекцій 2022 року від найкращих світових виробників",
    ABOUT_ITEM2: "Перше у світі шоу Nail Fashion Day",
    ABOUT_ITEM3: "Провідні спікери індустрії краси",
    ABOUT_ITEM4: "Майстер класи від зірок нігтьової естетики",
    ABOUT_ITEM5: "Новорічний корпоратив «Nail New Year» під запалюючий супровід кавєр- бенд «Wunderkind» та DJ",
    ROAD_MAP: "Карта проїзду",
    LOCATION: "ТЦ «Gorodok Gallery»",
    STATISTICS_VISITORS: "Відвідувачів повязаних з нейл індустрією",
    STATISTICS_NAILBUYERS: "Нейл байерів візьмуть участь у заході",
    STATISTICS_COMPANY: "Компаній виробників візьмуть участь у події",
    STATISTICS_EXPERTS: "Всесвітньо відомих експертів серед наших спікерів",
    SAFETY_MEASURES: "Заходи безпеки",
    PROTECTION_MEANS: 'Заходи захисту',
    PROTECTION_MEANS_SUBTITLE: 'Вхід на конференцію тільки в масці. Наявність антисептиків по периметру приміщення',
    TEMPERATURE_SCREENING: 'Температурний скрініг на вході.',
    TEMPERATURE_SCREENING_SUBTITLE: 'Вимірювання температури тіла кожному відвідувачу.',
    FOOD_TITLE: 'Безпечне харчування',
    FOOD_SUBTITLE: 'Під час кава-брейку кожній людині надається індівідуальний посуд',
    PASSPORT_TITLE: 'ПЛР-тест або паспорт вакцинації',
    RESTRICTIONS_TITLE: 'Відповідність вимогам МОЗ',
    RESTRICTIONS_SUBTITLE: 'Кількість відвідувачів обмежена згідно з правилами проведення масових заходів.',
    DISTANCE_TITLE: 'Соціальне дистанціювання',
    DISTANCE_SUBTITLE: 'Відстань між стільцями у конференц-залі не менше 1,5 метра.',
    FOOTER_COL_ADVERTISING: 'Розробка та створення сайту',
  }
};

export default localisation;