const localisation = {
  translation: {
    NAV_MENU_PLAN: "Пpo захiд",
    NAV_MENU_REGISTER: "Квитки",
    NAV_MENU_PARTICIPANTS: "Виробникам",
    NAV_MENU_SPEAKERS: "Спікери",
    NAV_MENU_DISCO: "Новорічна дискотека",
    BANNER_SUBTITLE: "Максимум можливостей - максимум задоволення!",
    REGISTRATION: "Реєстрація",
    BANNER_DATE: "15 грудня / середа",
    ABOUT_TITLE: "Вперше в Європі! Найбільший міжнародний форум нігтьової естетики",
    ABOUT_ITEM1: "Презентація нових колекцій 2022 року від найкращих світових виробників",
    ABOUT_ITEM2: "Перше у світі шоу Nail Fashion Day",
    ABOUT_ITEM3: "Виступи Топ-спікерів індустрії краси",
    ABOUT_ITEM4: "Найновіші тренди та технології від майстрів нігтьової естетики",
    ABOUT_ITEM5: "Вечірка та шоу-програма для всіх учасників форуму",
    ROAD_MAP: "Карта проїзду",
    LOCATION: "ТЦ «Gorodok Gallery»",
    STATISTICS_VISITORS: "Відвідувачів повязаних з нейл індустрією",
    STATISTICS_NAILBUYERS: "Нейл байерів візьмуть участь у заході",
    STATISTICS_COMPANY: "Провідних виробників nail індустрії",
    STATISTICS_EXPERTS: "Топ спікерів-практиків",
    PROGRAM_TITLE: 'В програмі форуму:',
    PROGRAM_ITEM: 'Реєстрація',
    PROGRAM_ITEM1: 'Працює DJ',
    PROGRAM_ITEM2: 'Вітальне слово організаторів',
    PROGRAM_ITEM3: 'Презентации',
    PROGRAM_ITEM4: 'Шоу Nail Fashion Day',
    PROGRAM_ITEM5: 'Новорічний корпоратив',
    PROGRAM_ITEM6: 'Спікер',
    BUTTON_CLICK: 'Згорнути',
    BUTTON_ALL: 'Вся програма',
    SAFETY_MEASURES: "Заходи безпеки",
    PROTECTION_MEANS: 'Заходи захисту',
    PROTECTION_MEANS_SUBTITLE: 'Вхід на конференцію тільки в масці. Наявність антисептиків по периметру приміщення',
    TEMPERATURE_SCREENING: 'Температурний скрініг на вході.',
    TEMPERATURE_SCREENING_SUBTITLE: 'Вимірювання температури тіла кожному відвідувачу.',
    FOOD_TITLE: 'Безпечне харчування',
    FOOD_SUBTITLE: 'Під час кава-брейку кожній людині надається індівідуальний посуд',
    PASSPORT_TITLE: 'ПЛР-тест або паспорт вакцинації',
    RESTRICTIONS_TITLE: 'Відповідність вимогам МОЗ',
    RESTRICTIONS_SUBTITLE: 'Кількість відвідувачів обмежена згідно з правилами проведення масових заходів.',
    DISTANCE_TITLE: 'Соціальне дистанціювання',
    DISTANCE_SUBTITLE: 'Відстань між стільцями у конференц-залі не менше 1,5 метра.',
    FOOTER_COL_ADVERTISING: 'Розробка та створення сайту',
    STILL: 'Є запитання щодо події?',
    STILL_WRITE: 'Пиши нам!',
    BUY_TICKET: 'Купити квиток',
    // BUY_TICKET1: 'Придбати квиток',
    MASTERS: 'майстрам',
    MEMBERS: 'участникам',
    BUYERS: 'байерам',
    LEARN_MORE: 'Залишились питання? Пиши/дзвони нам! На все дамо відповіді!',
    LEARN_MORE_WRITE: 'Написати',
    LEARN_MORE1: 'Виробник? Візьми участь!',
    LEARN_MORE_WRITE1: 'Подати заяву',
    LEARN_MORE_US: 'Готовий круто написати про нас? Співпрацюй!',
    LEARN_MORE_WRITE2: 'Співпрацювати',
    LEARN_MORE_MASTER: 'Досвідчений майстер або новачок? Приєднуйся!',
    LEARN_MORE_WRITE3: 'Приєднатися',
    LEARN_MORE_LOGO: 'Хочеш, щоб усі бачили твоє лого? Спонсуй!',
    LEARN_MORE_WRITE4: 'Спонсорувати',
    YOU_WANT: 'Найсучасніший Fashion Day індустрії краси!',
    YOU_WANT1: 'Якщо ви прагнете:',
    YOU_WANT2: 'дізнатися першими про тренди сезону 2022',
    YOU_WANT3: 'протестувати новинки світових брендів',
    YOU_WANT4: 'почути про тенденції нігтьової індустрії майбутнього',
    YOU_WANT5: 'надихнутися новими ідеями та знайти нові знайомства',
    ORGANIZER: 'Організатор:',
    ORGANIZER_DECS: 'Серія форумів про новітні технології та перспективні розробки в індустрії краси',
    ORGANIZER_AGITATION: 'Все, що вам потрібно - ',
    ORGANIZER_OR: 'або',
    BONUS: 'Приємний бонус гостям та учасникам - новорічний корпоратив під запальні хіти від Cover band «Wunderkind»',
    BONUS_GIFT: 'Подарунки від спонсорів та партнерів',
    BONUS_GIFT1: 'Необмежений простір для професійного росту та нетворкінгу!',
    BONUS_TEXT: 'Запалюємо разом',
    BONUS_TEXT1: 'Вчимося новому',
    BONUS_TEXT2: 'Ділимося кращим',
    BONUS_TEXT3: 'Посміхаємось щиро',
    BONUS_TEXT4: 'Ярмарок новинок, ділові контакти, перспективні зв’язки та відмінний настрій!',
    BONUS_TEXT5: '15 лютого 2021! Київ,',
    BONUS_TEXT6: 'Твій квиток у світ Nano Tech Nail чекає на тебе ТУТ:',
  }
};

export default localisation;